# Generated by Django 6.0.1 on 2026-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos')),
                ('type', models.CharField(max_length=100)),
                ('about_company', models.TextField()),
                ('work_space', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
